refactor: refactor public ports for relay and para chains
HugoByte/polkadot-kurtosis-package pull request #175
Opened 2024-01-09 12:07 UTC by riyasng12

## Description:
Refactored public ports for relay and para chains

### Commit Message

```bash
refactor: refactor public ports for relay and para chains
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

## Checklist:

- [X] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [X] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2024-01-09 12:31 UTC, shanithkk approved these changes

2024-01-09 12:31 UTC, shanithkk commented on parachain/parachain.star
> +def start_nodes(plan, args, relay_chain_ip, rpc_port = [[]], prometheus_port = [[]], lib2lib_port = [[]]):
@shreyasbhat0 , please review the logic behind the port passing in start_nodes function

2024-01-10 11:51 UTC, shanithkk approved these changes

2024-01-10 11:53 UTC, shanithkk requested changes

2024-01-10 11:53 UTC, shanithkk commented on package_io/utils.star
>                      if node["node-type"] in ["validator",  "full", "collator"]:
change node-type to node_type

2024-01-10 11:53 UTC, shanithkk commented on package_io/utils.star
> +        node["node-type"] = node["node-type"].lower()
follow same pattern for keys

2024-01-10 12:02 UTC, shanithkk approved these changes

2024-01-10 12:07 UTC, shreyasbhat0 approved these changes

2024-01-10 12:07 UTC, merged